<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountryCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       


        
        
            $countries = [["name"=>"Japan","code"=>"JP"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Finland","code"=>"FI"],
            ["name"=>"San Marino","code"=>"SM"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Australia","code"=>"AU"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"South Korea","code"=>"KR"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Costa Rica","code"=>"CR"],
            ["name"=>"Albania","code"=>"AL"],
            ["name"=>"Madagascar","code"=>"MG"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Finland","code"=>"FI"],
            ["name"=>"Palestinian Territory","code"=>"PS"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Ecuador","code"=>"EC"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Serbia","code"=>"RS"],
            ["name"=>"Cameroon","code"=>"CM"],
            ["name"=>"Comoros","code"=>"KM"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Finland","code"=>"FI"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Kazakhstan","code"=>"KZ"],
            ["name"=>"Malaysia","code"=>"MY"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Macedonia","code"=>"MK"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Mayotte","code"=>"YT"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Armenia","code"=>"AM"],
            ["name"=>"Bangladesh","code"=>"BD"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Kazakhstan","code"=>"KZ"],
            ["name"=>"Namibia","code"=>"NA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Comoros","code"=>"KM"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Serbia","code"=>"RS"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Spain","code"=>"ES"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Venezuela","code"=>"VE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Venezuela","code"=>"VE"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Pakistan","code"=>"PK"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Ecuador","code"=>"EC"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Kenya","code"=>"KE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Guatemala","code"=>"GT"],
            ["name"=>"Finland","code"=>"FI"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Bulgaria","code"=>"BG"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Denmark","code"=>"DK"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Egypt","code"=>"EG"],
            ["name"=>"Ireland","code"=>"IE"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Liechtenstein","code"=>"LI"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Uganda","code"=>"UG"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Italy","code"=>"IT"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Malaysia","code"=>"MY"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Ireland","code"=>"IE"],
            ["name"=>"Togo","code"=>"TG"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"South Korea","code"=>"KR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Ireland","code"=>"IE"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Slovenia","code"=>"SI"],
            ["name"=>"Ecuador","code"=>"EC"],
            ["name"=>"Syria","code"=>"SY"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Morocco","code"=>"MA"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Netherlands","code"=>"NL"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Afghanistan","code"=>"AF"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Benin","code"=>"BJ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Sudan","code"=>"SD"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Iran","code"=>"IR"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Palestinian Territory","code"=>"PS"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Burkina Faso","code"=>"BF"],
            ["name"=>"Bulgaria","code"=>"BG"],
            ["name"=>"Finland","code"=>"FI"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Slovenia","code"=>"SI"],
            ["name"=>"Panama","code"=>"PA"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Maldives","code"=>"MV"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Uganda","code"=>"UG"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Senegal","code"=>"SN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Cuba","code"=>"CU"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Netherlands","code"=>"NL"],
            ["name"=>"Cuba","code"=>"CU"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Serbia","code"=>"RS"],
            ["name"=>"Madagascar","code"=>"MG"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"United Kingdom","code"=>"GB"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Uzbekistan","code"=>"UZ"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Mozambique","code"=>"MZ"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Israel","code"=>"IL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Dominican Republic","code"=>"DO"],
            ["name"=>"Croatia","code"=>"HR"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Uruguay","code"=>"UY"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Belarus","code"=>"BY"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Afghanistan","code"=>"AF"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Armenia","code"=>"AM"],
            ["name"=>"Papua New Guinea","code"=>"PG"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"American Samoa","code"=>"AS"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Republic of the Congo","code"=>"CG"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Malaysia","code"=>"MY"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Ethiopia","code"=>"ET"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Luxembourg","code"=>"LU"],
            ["name"=>"Finland","code"=>"FI"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Estonia","code"=>"EE"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Bangladesh","code"=>"BD"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Mongolia","code"=>"MN"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Palestinian Territory","code"=>"PS"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Syria","code"=>"SY"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Puerto Rico","code"=>"PR"],
            ["name"=>"Dominican Republic","code"=>"DO"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Zambia","code"=>"ZM"],
            ["name"=>"Morocco","code"=>"MA"],
            ["name"=>"New Zealand","code"=>"NZ"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Uzbekistan","code"=>"UZ"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Jordan","code"=>"JO"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Venezuela","code"=>"VE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"East Timor","code"=>"TL"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"Belarus","code"=>"BY"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Aland Islands","code"=>"AX"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Myanmar","code"=>"MM"],
            ["name"=>"Pakistan","code"=>"PK"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Cuba","code"=>"CU"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Tunisia","code"=>"TN"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Germany","code"=>"DE"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Chile","code"=>"CL"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"United Arab Emirates","code"=>"AE"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Pakistan","code"=>"PK"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Germany","code"=>"DE"],
            ["name"=>"Uruguay","code"=>"UY"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"South Korea","code"=>"KR"],
            ["name"=>"Germany","code"=>"DE"],
            ["name"=>"Latvia","code"=>"LV"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mongolia","code"=>"MN"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Guatemala","code"=>"GT"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Slovenia","code"=>"SI"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Germany","code"=>"DE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Iran","code"=>"IR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Tajikistan","code"=>"TJ"],
            ["name"=>"Albania","code"=>"AL"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Chile","code"=>"CL"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Comoros","code"=>"KM"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Kazakhstan","code"=>"KZ"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Central African Republic","code"=>"CF"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Yemen","code"=>"YE"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Netherlands","code"=>"NL"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Cameroon","code"=>"CM"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Albania","code"=>"AL"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Malawi","code"=>"MW"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Italy","code"=>"IT"],
            ["name"=>"South Korea","code"=>"KR"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Germany","code"=>"DE"],
            ["name"=>"Croatia","code"=>"HR"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Macedonia","code"=>"MK"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mongolia","code"=>"MN"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"Nicaragua","code"=>"NI"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"South Korea","code"=>"KR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Latvia","code"=>"LV"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Macedonia","code"=>"MK"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Uruguay","code"=>"UY"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Tunisia","code"=>"TN"],
            ["name"=>"Nepal","code"=>"NP"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Paraguay","code"=>"PY"],
            ["name"=>"Ecuador","code"=>"EC"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Slovenia","code"=>"SI"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Palestinian Territory","code"=>"PS"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Senegal","code"=>"SN"],
            ["name"=>"Iran","code"=>"IR"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Kenya","code"=>"KE"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Chad","code"=>"TD"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Cuba","code"=>"CU"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Netherlands","code"=>"NL"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Egypt","code"=>"EG"],
            ["name"=>"Albania","code"=>"AL"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Lebanon","code"=>"LB"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Israel","code"=>"IL"],
            ["name"=>"Lithuania","code"=>"LT"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Malta","code"=>"MT"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Estonia","code"=>"EE"],
            ["name"=>"Venezuela","code"=>"VE"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Latvia","code"=>"LV"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Pakistan","code"=>"PK"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Albania","code"=>"AL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Tajikistan","code"=>"TJ"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Malaysia","code"=>"MY"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Hungary","code"=>"HU"],
            ["name"=>"Nepal","code"=>"NP"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Syria","code"=>"SY"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Croatia","code"=>"HR"],
            ["name"=>"Zambia","code"=>"ZM"],
            ["name"=>"Zambia","code"=>"ZM"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Dominican Republic","code"=>"DO"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Moldova","code"=>"MD"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Germany","code"=>"DE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Palestinian Territory","code"=>"PS"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Zambia","code"=>"ZM"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Bolivia","code"=>"BO"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Kuwait","code"=>"KW"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Yemen","code"=>"YE"],
            ["name"=>"Dominican Republic","code"=>"DO"],
            ["name"=>"Kenya","code"=>"KE"],
            ["name"=>"Israel","code"=>"IL"],
            ["name"=>"Malaysia","code"=>"MY"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Moldova","code"=>"MD"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Czech Republic","code"=>"CZ"],
            ["name"=>"Ireland","code"=>"IE"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Tanzania","code"=>"TZ"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Azerbaijan","code"=>"AZ"],
            ["name"=>"Syria","code"=>"SY"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Democratic Republic of the Congo","code"=>"CD"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Chile","code"=>"CL"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Croatia","code"=>"HR"],
            ["name"=>"Ireland","code"=>"IE"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"United Kingdom","code"=>"GB"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Germany","code"=>"DE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Cyprus","code"=>"CY"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Spain","code"=>"ES"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Armenia","code"=>"AM"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Panama","code"=>"PA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Ghana","code"=>"GH"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Kenya","code"=>"KE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Bosnia and Herzegovina","code"=>"BA"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Canada","code"=>"CA"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Kazakhstan","code"=>"KZ"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Saint Pierre and Miquelon","code"=>"PM"],
            ["name"=>"Jamaica","code"=>"JM"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"Mexico","code"=>"MX"],
            ["name"=>"Democratic Republic of the Congo","code"=>"CD"],
            ["name"=>"Laos","code"=>"LA"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Latvia","code"=>"LV"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Vietnam","code"=>"VN"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Yemen","code"=>"YE"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Botswana","code"=>"BW"],
            ["name"=>"Mauritius","code"=>"MU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Greece","code"=>"GR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Mongolia","code"=>"MN"],
            ["name"=>"Ukraine","code"=>"UA"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Norway","code"=>"NO"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Bolivia","code"=>"BO"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Argentina","code"=>"AR"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Niger","code"=>"NE"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Martinique","code"=>"MQ"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Croatia","code"=>"HR"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Costa Rica","code"=>"CR"],
            ["name"=>"Nigeria","code"=>"NG"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Honduras","code"=>"HN"],
            ["name"=>"Palestinian Territory","code"=>"PS"],
            ["name"=>"Niger","code"=>"NE"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Chile","code"=>"CL"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Honduras","code"=>"HN"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Switzerland","code"=>"CH"],
            ["name"=>"France","code"=>"FR"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Peru","code"=>"PE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"South Africa","code"=>"ZA"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Bulgaria","code"=>"BG"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Netherlands","code"=>"NL"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Bangladesh","code"=>"BD"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Ireland","code"=>"IE"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Indonesia","code"=>"ID"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Brazil","code"=>"BR"],
            ["name"=>"Iran","code"=>"IR"],
            ["name"=>"Thailand","code"=>"TH"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Japan","code"=>"JP"],
            ["name"=>"Colombia","code"=>"CO"],
            ["name"=>"United States","code"=>"US"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"China","code"=>"CN"],
            ["name"=>"Croatia","code"=>"HR"],
            ["name"=>"Syria","code"=>"SY"],
            ["name"=>"Bulgaria","code"=>"BG"],
            ["name"=>"Portugal","code"=>"PT"],
            ["name"=>"Sweden","code"=>"SE"],
            ["name"=>"Russia","code"=>"RU"],
            ["name"=>"Poland","code"=>"PL"],
            ["name"=>"Saudi Arabia","code"=>"SA"],
            ["name"=>"Ethiopia","code"=>"ET"],
            ["name"=>"Philippines","code"=>"PH"],
            ["name"=>"Guatemala","code"=>"GT"]];
        
        foreach ($countries as $country) {
        Country::create([
            
            "name" => $country["name"],
            "code" => $country["code"],
            
        ]);
    };
    }
}
